### ISSUE TITLE
can you update tu support async/await?

### ISSUE THREAD

**Issue by runhwguo** [scijs/get-pixels#31]
can you update to support async/await?

**Comment by rreusser** [comment]
Thanks for the suggestion, but I regret to inform you that the answer is no. For exactly equivalent functionality, any project that used this library may be forced to change its entire build configuration where a one-line wrapper like [apr-awaitify](https://www.npmjs.com/package/apr-awaitify) would suffice. I'm certainly open to different opinions, but generally speaking, I think it's much better to publish code in ES5 unless there's something to be gained by doing otherwise. Thanks for the suggestion though!
